[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@netlify/functions"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 8000